description: >
  Purge circle docker layer caching inspired from https://support.circleci.com/hc/en-us/articles/360007406013-How-can-I-remove-my-cached-docker-layers-

executor: base

steps:
  - setup_remote_docker:  { docker_layer_caching: true }
  - run: docker system prune -af